// Generated by CoffeeScript 1.9.0
$(function() {
  NCMB.initialize("APPLICATION_KEY", "CLIENT_KEY");
  return $("form").on("submit", function(e) {
    var message;
    e.preventDefault();
    message = $("#message").val();
    NCMB.Push.send({
      message: message,
      immediateDeliveryFlag: true,
      target: ['ios'],
      searchCondition: {}
    }).then(function(e) {
      console.info("success", e);
      $(".message").addClass("alert alert-success").html("作成されました");
      return setTimeout(function(e) {
        return $(".message").removeClass("alert alert-success").html("");
      }, 3000);
    }, function(e) {
      return console.error("error", e);
    });
    return false;
  });
});
